source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/omarchy/current/background
    blur_passes = 1
}

animations {
    enabled = false
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = JetBrainsMono Nerd Font
    font_size = 110
    color= rgba(251, 241, 199, 1.0)
    position = 60, 170
    halign = left
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%d/%m/%y"
    font_family = JetBrainsMono Nerd Font
    font_size = 22
    color= rgba(251, 241, 199, 1.0)
    position = 200, 50
    halign = left
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    position = 120, -140
    halign = left
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 6
    shadow_passes = 0
    dots_size = 0.3
    dots_spacing = 0.8
    fade_on_empty = true
}

auth {
    fingerprint:enabled = false
}
